# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppA' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pattern
    pod 'RxSwift', '~> 3.5'
    pod 'RxCocoa'

  #Statistic
    pod 'Fabric'
    pod 'Crashlytics'

  target 'AppATests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppAUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
